### ISSUE TITLE
Embedded Image Question (what am I doing wrong?)

### ISSUE THREAD

**Issue by jdgwf** [deeplook/svglib#164]
Getting the following error with the following SVG code ( made the test file as small as I could, for the image coudn't be attached).

My RegEx skills are rusty, but I believe the SVG code is valid.

> env) jeff@jdg-ubuntu:~/testing/py3$ python3 svg-to-pdf-test.py
> Traceback (most recent call last):
>   File "svg-to-pdf-test.py", line 4, in <module>
>     drawing = svg2rlg("test.svg")
>   File "/home/jeff/testing/py3/libs/svglib/svglib/svglib.py", line 1224, in svg2rlg
>     drawing = svgRenderer.render(svg)
>   File "/home/jeff/testing/py3/libs/svglib/svglib/svglib.py", line 522, in render
>     main_group = self.renderSvg(node, outermost=True)
>   File "/home/jeff/testing/py3/libs/svglib/svglib/svglib.py", line 639, in renderSvg
>     self.renderNode(child, group)
>   File "/home/jeff/testing/py3/libs/svglib/svglib/svglib.py", line 550, in renderNode
>     item = self.renderG(n, clipping=clipping)
>   File "/home/jeff/testing/py3/libs/svglib/svglib/svglib.py", line 667, in renderG
>     item = self.renderNode(child, parent=gr)
>   File "/home/jeff/testing/py3/libs/svglib/svglib/svglib.py", line 565, in renderNode
>     item = self.shape_converter.convertShape(name, n, clipping)
>   File "/home/jeff/testing/py3/libs/svglib/svglib/svglib.py", line 743, in convertShape
>     shape = getattr(self, method_name)(node)
>   File "/home/jeff/testing/py3/libs/svglib/svglib/svglib.py", line 1085, in convertImage
>     match = re.match(magic_re, xlink_href)
>   File "/home/jeff/testing/py3/env/lib/python3.6/re.py", line 172, in match
>     return _compile(pattern, flags).match(string)
> TypeError: expected string or bytes-like object

This breaks whether it's an embedded base64 or a file reference.

> &lt;svg version=&quot;1.1&quot; x=&quot;0px&quot; y=&quot;0px&quot; xml:space=&quot;preserve&quot; viewBox=&quot;0 0 2000 2600&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot;&gt;
> &lt;g&gt;
> &lt;rect x=&quot;0&quot; y=&quot;0&quot; width=&quot;2000&quot; height=&quot;2600&quot; fill=&quot;rgb(255,255,255)&quot;&gt;&lt;/rect&gt;
> &lt;rect rx=&quot;15&quot; ry=&quot;15&quot; x=&quot;10&quot; y=&quot;30&quot; width=&quot;700&quot; height=&quot;400&quot; fill=&quot;rgb(51,51,51)&quot;&gt;&lt;/rect&gt;
> &lt;rect rx=&quot;15&quot; ry=&quot;15&quot; x=&quot;12&quot; y=&quot;32&quot; width=&quot;696&quot; height=&quot;396&quot; fill=&quot;rgb(255,255,255)&quot;&gt;&lt;/rect&gt;
> &lt;rect rx=&quot;15&quot; ry=&quot;15&quot; x=&quot;45&quot; y=&quot;10&quot; width=&quot;630&quot; height=&quot;40&quot; fill=&quot;rgb(51,51,51)&quot;&gt;&lt;/rect&gt;
> &lt;text rx=&quot;15&quot; ry=&quot;15&quot; x=&quot;360&quot; y=&quot;42&quot; font-family=&quot;sans-serif&quot; fill=&quot;rgb(255,255,255)&quot; text-anchor=&quot;middle&quot; font-size=&quot;35&quot;&gt;Test&lt;/text&gt;
> &lt;image xlink:href=&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAYAAAAeP4ixAAAABmJLR0QAEgASABIPeHnLAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAB3RJTUUH4goMDiUX9oDPGgAAABl0RVh0Q29tbWVudABDcmVhdGVkIHdpdGggR0lNUFeBDhcAAANgSURBVGje7ZlNaBNBFMf/+5FNdpO0SWqiTdSqhfoBlooieihFwYNnDx48KHjzJHhVqAdviqAHL55EBE8i6kHBgwREFASjIraljbWaamvaJmn2e8dD9GB3NrtptSky7xJ48/HmN/vmvTcTLpVKEfwHwuM/EQbCQBgIA2EgDISBMJA1KOJSxcGeJ1Ckbmpn4tiwYcCw5lDVRvGpfBdVM9907Ez1JQrTpwEAXcoxDOSGXfM+Hd3t0m1OnEMmdgCKlIXAK+AIB4uo0Mxv+LH4CsXyNdioeoM0E44XIEKGKMlQpCzS8YMY/X4TU5UbnmMS8s6WdlYW+tGfu4RYeMsS40AIMYSEGOKRXqzvPIQPpauY0x6t3LV4TkJv+hQEIevZJyTGkYkeDzYfn8HAxstuCBqwuB792QuIh4b+zhkReQW5ePOFZmJDgebqTZ2lujUhFiyn7rYtRNGXOfP3DrscyjZt74zsCDRPUt5F1U/OPcTziRNwiOFq65D7IHKZ4CCfyw/xZuo8LHvR7T683HRsREojFTnqayMkdFL1qjEJ0xmDadco7i0iKR8ODkI4gln1PupGibYE3/GZ+BHfPoIQoeotp/ElHMegtiuhbOuuRYjljmbgAriNf/TifYIozXbjS3a0DsJxHAXE//1CCecQEdY1n3uZR5bnxNbySIM+6dI5sINsAbqi+/12qWnzovGVaks3Z4ODpJV9WNfzGLKUcfswJQBQo5e8fUXR8XeFEKhE8Qyx4W7Ptpo2HmgOSexcvVqrVVH1Ekq12/+8KBzcmockJjzyzIPlgxDioKKN4OP0lT+Kt6ViOyoEnzyzql9krv4WFXUENtFhmvOY0fLQrXe+4yr6hGfGbgtIVS9irDzcsoGaOo6O8DYIfGRFC81PDGIgewtd0T3tuVgRjqCmFQO765q+IZbrhWAgWOMgpcr9QIt0HM0jT/K/fkPtBVHtAlRj2refZs56XBM2AADCQkf7Hx/m6+/9XXDxDVW/MXEUe7N3EA1vaj/ITDXv22di4To0c4ZSESSRiO5uXNzbDTKr3YNhLfickTIKXy42dcOaVqSW86v6rrWgj/nnK/MZXnw+jsnyPdSNr7AdHYRY0K0ySvNP8XrqJCqqu7bj2J+hDISBMBAGwkAYCANhIAzET34C46oZUH82mSYAAAAASUVORK5CYII=&quot; x=&quot;100&quot; y=&quot;140&quot; height=&quot;50&quot; width=&quot;50&quot;&gt;&lt;/image&gt;
> &lt;image xlink:href=&quot;data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEBLAEsAAD//gATQ3JlYXRlZCB3aXRoIEdJTVD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wgARCAAyADIDAREAAhEBAxEB/8QAGgABAQADAQEAAAAAAAAAAAAAAAUCBAYDCP/EABkBAQEBAQEBAAAAAAAAAAAAAAADBAIBBf/aAAwDAQACEAMQAAAB+bAAAD254o8R2eeJtL7/ABGVTRr9d0Zw6zNg3uJePvWHqJXVzGnfRnDrM2Da5nzt9l6OSPXTymn6FiWba5nn55Ats6jPgn0tBtrAAAAAAA//xAAgEAACAgIBBQEAAAAAAAAAAAADBAIFAAETERIVIDQw/9oACAEBAAEFAvcItmIasKDPCnw6ZV5xpj70YE155X/bY4xKcIsa6naNxGuCiLHK/wC2xx1jaoFnZt2DPbz3ARjFlc2NWTdnE83rIbK4i7CTdwKWrF+DY/3/AP/EACQRAAICAQIGAwEAAAAAAAAAAAECAAMREBIEFDEzQnEgMkBR/9oACAEDAQE/AfmzbRkxb1bOJzKRLFcZE5lIrhxkaXdsyny9RAD1ifVoi7lacOrKTkaXdsyny9StN7Yj1Cus4iZ2kgzh2Yk5Ol1bWdJXQVBzKqGRsmMu4YM5Zv7KajWcn8H/xAAhEQADAAEDBAMAAAAAAAAAAAAAAQIRAxAxEhMyQSBAYf/aAAgBAgEBPwH5t4WRaiZ3UKlR3ZE1XG1+JHsX6LhkrKZpJra/Ej2Sup4KhTLJ4ZpNt7XLrgnTxkjTcvI1lYO0yIc/Q//EACkQAAIBAwIEBQUAAAAAAAAAAAECAAMREgQxECFBcSAiUXORMkBhcrH/2gAIAQEABj8C8aoNz6xMivmbHlPqp/MCsN9rdZfyj8EzFxY8KXeaf3RFw3yE037H+TT3bFbm/wASmUdWI9Dwpd5p/dEzAvKOVgBewHaUFZA4a45yngirz6DgxdSb7WEpWUhUbI3hRQwN+sV13EBNI5jaIFDAg9fsP//EACQQAQACAQIEBwAAAAAAAAAAAAEAESEgMUFxsdEQQIGhwfDx/9oACAEBAAE/IdaNg9DsmYOoWd30n7TtLn7v5wHS/MdIx+faL9yKomi8XmBa+zl2t81o5ojhk3saK9QViFM6mTJL0WUGw2b9oiKuaZw8E3tLApvKNq8Q1Hz0NkrrN7ruLc57VQ85ZnA1O/kP/9oADAMBAAIAAwAAABCSSSdsFR5a+PN0w3rSSSSSSSSf/8QAJBEBAAIBAgQHAAAAAAAAAAAAAQARITGxEFFh8CBAQXGRodH/2gAIAQMBAT8Q8ZPpExI4L7zOk/X7FCaaxFotl0eJ3kSTldok9g3JiBbRXzCBgeJ3EIm1PUs1vKKVVQ2Zxz4AA6lispUBsV30gPpMBUBTFqGfIf/EAB8RAQACAQQDAQAAAAAAAAAAAAEAESEQMWGxIEChwf/aAAgBAgEBPxDzJlLmjacbDLIg1mGXo3p1MIrwnyfswAzEGytN6dTM4lDS1g1UUW3oaCiGzlJYTCZQFocRlX0P/8QAJBABAAIBAwQBBQAAAAAAAAAAAQARITFBYRBxkfBRIECBobH/2gAIAQEAAT8Q+u/loEDzQzdb3VaC2MY6QzUvpFFdUb3kxzE4Yu7ThpH7j5BLM2D5Hc6ehwz0e8MQz6qDsxvtKrCiF93+hAMhqtS1eT5isy1CEGtcnTL06M9HvLHzTQyxdKlSgLkb1YhWbEmsBG3I/MdpwSU2NHQHXGuHLKlXZpLT6YGZoA1pe8HDACoPCjGAM3o/I8JZDK8hY8pq1niLi1UDSsUvsP/Z&quot; x=&quot;100&quot; y=&quot;200&quot; height=&quot;50&quot; width=&quot;50&quot;&gt;&lt;/image&gt;
> 
> &lt;/g&gt;
> 
> &lt;/svg&gt;

**Comment by jdgwf** [comment]
It's got to be something in my hand-written svg. An embedded inkscape with the same images file works fine.

**Comment by jdgwf** [comment]
FYI It was my SVG Headers.
replacing the following element with:

> &lt;svg
>    xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
>    xmlns:cc=&quot;http://creativecommons.org/ns#&quot;
>    xmlns:rdf=&quot;http://www.w3.org/1999/02/22-rdf-syntax-ns#&quot;
>    xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;
>    xmlns=&quot;http://www.w3.org/2000/svg&quot;
>    xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;
>    id=&quot;svg8&quot;
>    version=&quot;1.1&quot;
>    viewBox=&quot;0 0 2000 2600&quot;
>    height=&quot;2000&quot;
>    width=&quot;2600&quot;&gt;
> 
>
