### ISSUE TITLE
Division by Zero Error

### ISSUE THREAD

**Issue by bbowles-personal** [deeplook/svglib#188]
Got this when replacing prod code with current code: 

```Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\decompose_svg\decompose_svg.py", line 153, in run_with_filepath
    do_blob_test=do_blob_test)
  File "C:\ProgramData\Anaconda3\lib\site-packages\decompose_svg\decompose_svg.py", line 31, in build_tree_bfs
    base_im = svg_string_to_png_bytes(etree.tostring(svg_root))
  File "C:\ProgramData\Anaconda3\lib\site-packages\decompose_svg\decompose_svg.py", line 191, in svg_string_to_png_bytes    png_bytes = get_png_bytes(svg_string)
  File "C:\ProgramData\Anaconda3\lib\site-packages\decompose_svg\decompose_svg.py", line 186, in get_png_bytes
    renderPM.drawToFile(drawing, png_bytes_temp, fmt="PNG")
  File "C:\ProgramData\Anaconda3\lib\site-packages\reportlab\graphics\renderPM.py", line 680, in drawToFile
    c = drawToPMCanvas(d, dpi=dpi, bg=bg, configPIL=configPIL, showBoundary=showBoundary)
  File "C:\ProgramData\Anaconda3\lib\site-packages\reportlab\graphics\renderPM.py", line 666, in drawToPMCanvas
    draw(d, c, 0, 0, showBoundary=showBoundary)
  File "C:\ProgramData\Anaconda3\lib\site-packages\reportlab\graphics\renderPM.py", line 51, in draw
    R.draw(renderScaledDrawing(drawing), canvas, x, y, showBoundary=showBoundary)
  File "C:\ProgramData\Anaconda3\lib\site-packages\reportlab\graphics\renderbase.py", line 205, in draw
    self.drawNode(drawing)
  File "C:\ProgramData\Anaconda3\lib\site-packages\reportlab\graphics\renderPM.py", line 108, in drawNode
    self.drawNodeDispatcher(node)
  File "C:\ProgramData\Anaconda3\lib\site-packages\reportlab\graphics\renderbase.py", line 286, in drawNodeDispatcher
    self.drawGroup(node)
  File "C:\ProgramData\Anaconda3\lib\site-packages\reportlab\graphics\renderbase.py", line 317, in drawGroup
    self.drawNode(node)
  File "C:\ProgramData\Anaconda3\lib\site-packages\reportlab\graphics\renderPM.py", line 111, in drawNode
    self.pop()
  File "C:\ProgramData\Anaconda3\lib\site-packages\reportlab\graphics\renderPM.py", line 60, in pop
    self._tracker.pop()
  File "C:\ProgramData\Anaconda3\lib\site-packages\reportlab\graphics\renderbase.py", line 112, in pop
    reverseDelta[key] = inverse(lastDelta['transform'])
  File "C:\ProgramData\Anaconda3\lib\site-packages\reportlab\graphics\renderbase.py", line 16, in inverse
    R = [A[3]/det, -A[1]/det, -A[2]/det, A[0]/det]
ZeroDivisionError: float division by zero
```

**Comment by deeplook** [comment]
So what do you recommend to reproduce this?

**Comment by claudep** [comment]
Please reopen when you can provide a sample file to reproduce (or some test code).
