### ISSUE TITLE
On exporting to png/pdf via reportlab: float division by zero

### ISSUE THREAD

**Issue by kenomaerz** [deeplook/svglib#205]
I tried to do the png/pdf conversion from the main Readme of svglib, and got a float division by zero error.

Tested on: svglib 0.9.0 and newest on pypi today 
OS: Windows, python 3.7.3

```
drawing = svg2rlg("test.svg") # Line 
#renderPDF.drawToFile(drawing, "file.pdf") #fails if uncommented as well
renderPM.drawToFile(drawing, "file.png", fmt="PNG") #fails, Line 82 from stacktrace below
```

both calls throw an exception (the latter only if the previous is commented out, obviously.
test.svg: https://www.dropbox.com/s/2w5ax47neb6j1h4/test.svg?dl=0

Stacktrace:

```
Traceback (most recent call last):
  File "bubble/bubble.py", line 87, in <module>
    bubblify_preset("test.svg", "result.svg", "cami")
  File "bubble/bubble.py", line 8, in bubblify_preset
    bubblify(source, preset[0], preset[1], target)
  File "bubble/bubble.py", line 35, in bubblify
    export(tree, target)
  File "bubble/bubble.py", line 82, in export
    renderPM.drawToFile(drawing, "file.png", fmt="PNG")
  File "C:\Users\maerz\.virtualenvs\iconbubble-KO_YSgnj\lib\site-packages\reportlab\graphics\renderPM.py", line 680, in drawToFile
    c = drawToPMCanvas(d, dpi=dpi, bg=bg, configPIL=configPIL, showBoundary=showBoundary)
  File "C:\Users\maerz\.virtualenvs\iconbubble-KO_YSgnj\lib\site-packages\reportlab\graphics\renderPM.py", line 666, in drawToPMCanvas
    draw(d, c, 0, 0, showBoundary=showBoundary)
  File "C:\Users\maerz\.virtualenvs\iconbubble-KO_YSgnj\lib\site-packages\reportlab\graphics\renderPM.py", line 51, in draw
    R.draw(renderScaledDrawing(drawing), canvas, x, y, showBoundary=showBoundary)
  File "C:\Users\maerz\.virtualenvs\iconbubble-KO_YSgnj\lib\site-packages\reportlab\graphics\renderbase.py", line 205, in draw
    self.drawNode(drawing)
  File "C:\Users\maerz\.virtualenvs\iconbubble-KO_YSgnj\lib\site-packages\reportlab\graphics\renderPM.py", line 108, in drawNode
    self.drawNodeDispatcher(node)
  File "C:\Users\maerz\.virtualenvs\iconbubble-KO_YSgnj\lib\site-packages\reportlab\graphics\renderbase.py", line 286, in drawNodeDispatcher
    self.drawGroup(node)
  File "C:\Users\maerz\.virtualenvs\iconbubble-KO_YSgnj\lib\site-packages\reportlab\graphics\renderbase.py", line 317, in drawGroup
    self.drawNode(node)
  File "C:\Users\maerz\.virtualenvs\iconbubble-KO_YSgnj\lib\site-packages\reportlab\graphics\renderPM.py", line 111, in drawNode
    self.pop()
  File "C:\Users\maerz\.virtualenvs\iconbubble-KO_YSgnj\lib\site-packages\reportlab\graphics\renderPM.py", line 60, in pop
    self._tracker.pop()
  File "C:\Users\maerz\.virtualenvs\iconbubble-KO_YSgnj\lib\site-packages\reportlab\graphics\renderbase.py", line 112, in pop
    reverseDelta[key] = inverse(lastDelta['transform'])
  File "C:\Users\maerz\.virtualenvs\iconbubble-KO_YSgnj\lib\site-packages\reportlab\graphics\renderbase.py", line 16, in inverse
    R = [A[3]/det, -A[1]/det, -A[2]/det, A[0]/det]
ZeroDivisionError: float division by zero

```

**Comment by claudep** [comment]
Thanks, that was already reported in #195. I just pushed the patch I prepared to fix this issue. If you could confirm it fixes your problem, would be nice.

**Comment by kenomaerz** [comment]
Wow, thanks for the near immediate response. I can confirm that the current master exports correctly. Looking forward to the new release!
