### ISSUE TITLE
svglib failing to open bad svg files

### ISSUE THREAD

**Issue by AAlphaDEV** [deeplook/svglib#236]
This is not really an issue, but I had some problems trying to open an svg file.
It's about elliptical arc in a path node :
the file I have would write it like this : `a1.178 1.178 0 00-.078.391`
where the correct way should be something like : `a1.178 1.178 0 0 0 -.078.391` (notice the space between the two zeros)
So svglib doesn't recognize every parameters and throws an exception

I wrote a script to patch these svg files to be opened by svglib but idk if it's worth implementing this in the actual library, I'm just reporting the issue.

Another thing : firefox and other svg softwares like inkscape didn't have any issue with opening these files.
Let me know if something was not clear about the issue i had.

(Error triggered by that issue)
`Traceback (most recent call last):
  File "svg.py", line 4, in <module>
    drawing = svg2rlg("score_0.svg")
  File "G:\Programmes\Python3.8.0\lib\site-packages\svglib\svglib.py", line 1422, in svg2rlg
    drawing = svgRenderer.render(svg_root)
  File "G:\Programmes\Python3.8.0\lib\site-packages\svglib\svglib.py", line 580, in render
    main_group = self.renderSvg(node, outermost=True)
  File "G:\Programmes\Python3.8.0\lib\site-packages\svglib\svglib.py", line 834, in renderSvg
    self.renderNode(child, group)
  File "G:\Programmes\Python3.8.0\lib\site-packages\svglib\svglib.py", line 643, in renderNode
    item = self.shape_converter.convertShape(name, n, clipping)
  File "G:\Programmes\Python3.8.0\lib\site-packages\svglib\svglib.py", line 945, in convertShape
    shape = getattr(self, method_name)(node)
  File "G:\Programmes\Python3.8.0\lib\site-packages\svglib\svglib.py", line 1257, in convertPath
    rx, ry, phi, fA, fS, x2, y2 = nums
ValueError: not enough values to unpack (expected 7, got 5)`

**Comment by claudep** [comment]
Many thanks for your report. This was very recently fixed in master by d730b2bdfe87b.

**Comment by AAlphaDEV** [comment]
Ok sry
Thank you for your quick answer
