### ISSUE TITLE
Unable to convert svg to png

### ISSUE THREAD

**Issue by jamessappy** [deeplook/svglib#346]
Hi,

I'm trying to convert a svg file to png. I've used the following code:
          
          _from svglib.svglib import svg2rlg
          from reportlab.graphics import renderPM_
          
          _drawing = svg2rlg(svg_path)
          renderPM.drawToFile(drawing, png_path, fmt= 'PNG')_

I receive the following error message:

          _AttributeError: 'lxml.etree._Element' object has no attribute 'ancestors'. Did you mean: 'iterancestors'?_

I'm not exactly sure what my issue here is, thought maybe it was my version but I've updated python as well as the svglib and reportlab libraries and still haven't had any luck.

Thanks!

**Comment by claudep** [comment]
I think a full error traceback could help spotting the issue more precisely.

**Comment by jamessappy** [comment]
Are you referencing this?

_Traceback (most recent call last):
  File "c:\Users\James\Desktop\HeadlessConvertToPNG.py", line 8, in <module>
    drawing = svg2rlg(svg_path)
  File "C:\Users\James\AppData\Local\Programs\Python\Python310\lib\site-packages\svglib\svglib.py", line 1468, in svg2rlg
    drawing = svgRenderer.render(svg_root)
  File "C:\Users\James\AppData\Local\Programs\Python\Python310\lib\site-packages\svglib\svglib.py", line 553, in render
    main_group = self.renderSvg(node, outermost=True)
  File "C:\Users\James\AppData\Local\Programs\Python\Python310\lib\site-packages\svglib\svglib.py", line 834, in renderSvg
    self.renderNode(child, group)
  File "C:\Users\James\AppData\Local\Programs\Python\Python310\lib\site-packages\svglib\svglib.py", line 584, in renderNode
    item = self.renderG(n, clipping=clipping)
  File "C:\Users\James\AppData\Local\Programs\Python\Python310\lib\site-packages\svglib\svglib.py", line 868, in renderG
    matches = rules.match(self)
  File "C:\Users\James\AppData\Local\Programs\Python\Python310\lib\site-packages\cssselect2\__init__.py", line 93, in match
    self.add_relevant_selectors(
  File "C:\Users\James\AppData\Local\Programs\Python\Python310\lib\site-packages\cssselect2\__init__.py", line 120, in add_relevant_selectors
    if test(element):
  File "<string>", line 1, in <lambda>  File "C:\Users\James\AppData\Local\Programs\Python\Python310\lib\site-packages\svglib\svglib.py", line 503, in __getattr__
    return getattr(self.object, name)AttributeError: 'lxml.etree._Element' object has no attribute 'ancestors'. Did you mean: 'iterancestors'?PS C:\Users\James\Desktop_>

**Comment by claudep** [comment]
Thanks, yes, it helps. Would it be possible to also have the SVG file that triggers this error?

**Comment by jamessappy** [comment]
I am using version 1.3.0 of the svlib library. 
I've also attached the .svg file that I'm trying to convert.

![NewSunPath](https://user-images.githubusercontent.com/73321676/170405905-7d3b2caa-8621-4729-9fa7-83fffb2b1069.svg)

**Comment by claudep** [comment]
Thanks, I was able to reproduce the issue, a first step to resolution :-)
